eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8003
spring:
  application:
    name: spring-cloud-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: spring-cloud-consumer-rest
    api-b:
      path: /api-b/**
      serviceId: spring-cloud-consumer