eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8002
spring:
  application:
    name: spring-cloud-consumer-rest
